### ISSUE TITLE
TypeError: render_fit() missing 1 required positional argument: 'height'

### ISSUE THREAD

**Issue by attmore** [vindolin/ninepatch#4]
> ninepatch wrap img_card_b_body.9.png img_to_wrap.png wraped.png 

then got 

  File "/lib/python3.6/site-packages/ninepatch/__init__.py", line 236, in render_wrap
    scaled_image = self.render_fit(image.size)
TypeError: render_fit() missing 1 required positional argument: 'height'

**Comment by attmore** [comment]
in render_wrap function

change 
> scaled_image = self.render_fit(image.size)
to
> scaled_image = self.render_fit(image.size[0], image.size[1])
works for me

**Comment by vindolin** [comment]
Fixed in the repository (86f25813eb2ae9da6a43f1f5c909e852ced70b5a).

Now I'm having trouble with the README.md rendering on the PyPI test server.
Will upload to PyPI when I've figured that out..
