### ISSUE TITLE
Not working with Pillow 10.0.0

### ISSUE THREAD

**Issue by helgeerbe** [vindolin/ninepatch#6]
Error was reported here https://github.com/helgeerbe/picframe/issues/326

With Pillow 10.0.0 ANTIALIAS was depricated (https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants)

render() is defined as
````python
 def render(self, width, height, img_filter=Image.ANTIALIAS, cache=False):
````

**Comment by vindolin** [comment]
Thanks for reporting. Fixed already in the repo. I will update the pypi package in the coming days, when I've sorted the 2FA issue I'm having.

**Comment by helgeerbe** [comment]
Can up update PyPi? There is an security issue with Pillow < 10.0.1
